/*
 * Generated by gdbus-codegen 2.40.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "dbus_dmovie.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.deepin.DeepinMovie
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:DBusDmovie
 * @title: DBusDmovie
 * @short_description: Generated C code for the com.deepin.DeepinMovie D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-deepin-DeepinMovie.top_of_page">com.deepin.DeepinMovie</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.deepin.DeepinMovie ---- */

static const _ExtendedGDBusArgInfo _dbus_dmovie__method_info_play_paths_IN_ARG_pathList =
{
  {
    -1,
    (gchar *) "pathList",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _dbus_dmovie__method_info_play_paths_IN_ARG_pointers[] =
{
  &_dbus_dmovie__method_info_play_paths_IN_ARG_pathList,
  NULL
};

static const _ExtendedGDBusMethodInfo _dbus_dmovie__method_info_play_paths =
{
  {
    -1,
    (gchar *) "PlayPaths",
    (GDBusArgInfo **) &_dbus_dmovie__method_info_play_paths_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-play-paths",
  FALSE
};

static const _ExtendedGDBusMethodInfo _dbus_dmovie__method_info_play =
{
  {
    -1,
    (gchar *) "Play",
    NULL,
    NULL,
    NULL
  },
  "handle-play",
  FALSE
};

static const _ExtendedGDBusMethodInfo _dbus_dmovie__method_info_pause =
{
  {
    -1,
    (gchar *) "Pause",
    NULL,
    NULL,
    NULL
  },
  "handle-pause",
  FALSE
};

static const _ExtendedGDBusMethodInfo _dbus_dmovie__method_info_stop =
{
  {
    -1,
    (gchar *) "Stop",
    NULL,
    NULL,
    NULL
  },
  "handle-stop",
  FALSE
};

static const _ExtendedGDBusArgInfo _dbus_dmovie__method_info_set_uri_IN_ARG_uri =
{
  {
    -1,
    (gchar *) "uri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _dbus_dmovie__method_info_set_uri_IN_ARG_pointers[] =
{
  &_dbus_dmovie__method_info_set_uri_IN_ARG_uri,
  NULL
};

static const _ExtendedGDBusMethodInfo _dbus_dmovie__method_info_set_uri =
{
  {
    -1,
    (gchar *) "SetUri",
    (GDBusArgInfo **) &_dbus_dmovie__method_info_set_uri_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-uri",
  FALSE
};

static const _ExtendedGDBusArgInfo _dbus_dmovie__method_info_seek_IN_ARG_position =
{
  {
    -1,
    (gchar *) "position",
    (gchar *) "x",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _dbus_dmovie__method_info_seek_IN_ARG_pointers[] =
{
  &_dbus_dmovie__method_info_seek_IN_ARG_position,
  NULL
};

static const _ExtendedGDBusMethodInfo _dbus_dmovie__method_info_seek =
{
  {
    -1,
    (gchar *) "Seek",
    (GDBusArgInfo **) &_dbus_dmovie__method_info_seek_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-seek",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _dbus_dmovie__method_info_pointers[] =
{
  &_dbus_dmovie__method_info_play_paths,
  &_dbus_dmovie__method_info_play,
  &_dbus_dmovie__method_info_pause,
  &_dbus_dmovie__method_info_stop,
  &_dbus_dmovie__method_info_set_uri,
  &_dbus_dmovie__method_info_seek,
  NULL
};

static const _ExtendedGDBusPropertyInfo _dbus_dmovie__property_info_volume =
{
  {
    -1,
    (gchar *) "Volume",
    (gchar *) "d",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "volume",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _dbus_dmovie__property_info_mute =
{
  {
    -1,
    (gchar *) "Mute",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "mute",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _dbus_dmovie__property_info_duration =
{
  {
    -1,
    (gchar *) "Duration",
    (gchar *) "x",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "duration",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _dbus_dmovie__property_info_position =
{
  {
    -1,
    (gchar *) "Position",
    (gchar *) "x",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "position",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _dbus_dmovie__property_info_pointers[] =
{
  &_dbus_dmovie__property_info_volume,
  &_dbus_dmovie__property_info_mute,
  &_dbus_dmovie__property_info_duration,
  &_dbus_dmovie__property_info_position,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _dbus_dmovie__interface_info =
{
  {
    -1,
    (gchar *) "com.deepin.DeepinMovie",
    (GDBusMethodInfo **) &_dbus_dmovie__method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_dbus_dmovie__property_info_pointers,
    NULL
  },
  "",
};


/**
 * dbus_dmovie__interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-deepin-DeepinMovie.top_of_page">com.deepin.DeepinMovie</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
dbus_dmovie__interface_info (void)
{
  return (GDBusInterfaceInfo *) &_dbus_dmovie__interface_info.parent_struct;
}

/**
 * dbus_dmovie__override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #DBusDmovie interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
dbus_dmovie__override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "volume");
  g_object_class_override_property (klass, property_id_begin++, "mute");
  g_object_class_override_property (klass, property_id_begin++, "duration");
  g_object_class_override_property (klass, property_id_begin++, "position");
  return property_id_begin - 1;
}



/**
 * DBusDmovie:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-deepin-DeepinMovie.top_of_page">com.deepin.DeepinMovie</link>.
 */

/**
 * DBusDmovieIface:
 * @parent_iface: The parent interface.
 * @handle_pause: Handler for the #DBusDmovie::handle-pause signal.
 * @handle_play: Handler for the #DBusDmovie::handle-play signal.
 * @handle_play_paths: Handler for the #DBusDmovie::handle-play-paths signal.
 * @handle_seek: Handler for the #DBusDmovie::handle-seek signal.
 * @handle_set_uri: Handler for the #DBusDmovie::handle-set-uri signal.
 * @handle_stop: Handler for the #DBusDmovie::handle-stop signal.
 * @get_duration: Getter for the #DBusDmovie:duration property.
 * @get_mute: Getter for the #DBusDmovie:mute property.
 * @get_position: Getter for the #DBusDmovie:position property.
 * @get_volume: Getter for the #DBusDmovie:volume property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-deepin-DeepinMovie.top_of_page">com.deepin.DeepinMovie</link>.
 */

typedef DBusDmovieIface DBusDmovieInterface;
G_DEFINE_INTERFACE (DBusDmovie, dbus_dmovie_, G_TYPE_OBJECT);

static void
dbus_dmovie__default_init (DBusDmovieIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * DBusDmovie::handle-play-paths:
   * @object: A #DBusDmovie.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_pathList: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-deepin-DeepinMovie.PlayPaths">PlayPaths()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call dbus_dmovie__complete_play_paths() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-play-paths",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (DBusDmovieIface, handle_play_paths),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * DBusDmovie::handle-play:
   * @object: A #DBusDmovie.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-deepin-DeepinMovie.Play">Play()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call dbus_dmovie__complete_play() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-play",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (DBusDmovieIface, handle_play),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * DBusDmovie::handle-pause:
   * @object: A #DBusDmovie.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-deepin-DeepinMovie.Pause">Pause()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call dbus_dmovie__complete_pause() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-pause",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (DBusDmovieIface, handle_pause),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * DBusDmovie::handle-stop:
   * @object: A #DBusDmovie.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-deepin-DeepinMovie.Stop">Stop()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call dbus_dmovie__complete_stop() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-stop",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (DBusDmovieIface, handle_stop),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * DBusDmovie::handle-set-uri:
   * @object: A #DBusDmovie.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uri: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-deepin-DeepinMovie.SetUri">SetUri()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call dbus_dmovie__complete_set_uri() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-uri",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (DBusDmovieIface, handle_set_uri),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * DBusDmovie::handle-seek:
   * @object: A #DBusDmovie.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_position: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-deepin-DeepinMovie.Seek">Seek()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call dbus_dmovie__complete_seek() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-seek",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (DBusDmovieIface, handle_seek),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_INT64);

  /* GObject properties for D-Bus properties: */
  /**
   * DBusDmovie:volume:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-deepin-DeepinMovie.Volume">"Volume"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_double ("volume", "Volume", "Volume", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * DBusDmovie:mute:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-deepin-DeepinMovie.Mute">"Mute"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("mute", "Mute", "Mute", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * DBusDmovie:duration:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-deepin-DeepinMovie.Duration">"Duration"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_int64 ("duration", "Duration", "Duration", G_MININT64, G_MAXINT64, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * DBusDmovie:position:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-deepin-DeepinMovie.Position">"Position"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_int64 ("position", "Position", "Position", G_MININT64, G_MAXINT64, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * dbus_dmovie__get_volume: (skip)
 * @object: A #DBusDmovie.
 *
 * Gets the value of the <link linkend="gdbus-property-com-deepin-DeepinMovie.Volume">"Volume"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gdouble
dbus_dmovie__get_volume (DBusDmovie *object)
{
  return DBUS_DMOVIE__GET_IFACE (object)->get_volume (object);
}

/**
 * dbus_dmovie__set_volume: (skip)
 * @object: A #DBusDmovie.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-deepin-DeepinMovie.Volume">"Volume"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
dbus_dmovie__set_volume (DBusDmovie *object, gdouble value)
{
  g_object_set (G_OBJECT (object), "volume", value, NULL);
}

/**
 * dbus_dmovie__get_mute: (skip)
 * @object: A #DBusDmovie.
 *
 * Gets the value of the <link linkend="gdbus-property-com-deepin-DeepinMovie.Mute">"Mute"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean
dbus_dmovie__get_mute (DBusDmovie *object)
{
  return DBUS_DMOVIE__GET_IFACE (object)->get_mute (object);
}

/**
 * dbus_dmovie__set_mute: (skip)
 * @object: A #DBusDmovie.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-deepin-DeepinMovie.Mute">"Mute"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
dbus_dmovie__set_mute (DBusDmovie *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "mute", value, NULL);
}

/**
 * dbus_dmovie__get_duration: (skip)
 * @object: A #DBusDmovie.
 *
 * Gets the value of the <link linkend="gdbus-property-com-deepin-DeepinMovie.Duration">"Duration"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gint64
dbus_dmovie__get_duration (DBusDmovie *object)
{
  return DBUS_DMOVIE__GET_IFACE (object)->get_duration (object);
}

/**
 * dbus_dmovie__set_duration: (skip)
 * @object: A #DBusDmovie.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-deepin-DeepinMovie.Duration">"Duration"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
dbus_dmovie__set_duration (DBusDmovie *object, gint64 value)
{
  g_object_set (G_OBJECT (object), "duration", value, NULL);
}

/**
 * dbus_dmovie__get_position: (skip)
 * @object: A #DBusDmovie.
 *
 * Gets the value of the <link linkend="gdbus-property-com-deepin-DeepinMovie.Position">"Position"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gint64
dbus_dmovie__get_position (DBusDmovie *object)
{
  return DBUS_DMOVIE__GET_IFACE (object)->get_position (object);
}

/**
 * dbus_dmovie__set_position: (skip)
 * @object: A #DBusDmovie.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-deepin-DeepinMovie.Position">"Position"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
dbus_dmovie__set_position (DBusDmovie *object, gint64 value)
{
  g_object_set (G_OBJECT (object), "position", value, NULL);
}

/**
 * dbus_dmovie__call_play_paths:
 * @proxy: A #DBusDmovieProxy.
 * @arg_pathList: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.PlayPaths">PlayPaths()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call dbus_dmovie__call_play_paths_finish() to get the result of the operation.
 *
 * See dbus_dmovie__call_play_paths_sync() for the synchronous, blocking version of this method.
 */
void
dbus_dmovie__call_play_paths (
    DBusDmovie *proxy,
    const gchar *arg_pathList,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "PlayPaths",
    g_variant_new ("(s)",
                   arg_pathList),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * dbus_dmovie__call_play_paths_finish:
 * @proxy: A #DBusDmovieProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_dmovie__call_play_paths().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with dbus_dmovie__call_play_paths().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_play_paths_finish (
    DBusDmovie *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_play_paths_sync:
 * @proxy: A #DBusDmovieProxy.
 * @arg_pathList: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.PlayPaths">PlayPaths()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See dbus_dmovie__call_play_paths() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_play_paths_sync (
    DBusDmovie *proxy,
    const gchar *arg_pathList,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "PlayPaths",
    g_variant_new ("(s)",
                   arg_pathList),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_play:
 * @proxy: A #DBusDmovieProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.Play">Play()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call dbus_dmovie__call_play_finish() to get the result of the operation.
 *
 * See dbus_dmovie__call_play_sync() for the synchronous, blocking version of this method.
 */
void
dbus_dmovie__call_play (
    DBusDmovie *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Play",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * dbus_dmovie__call_play_finish:
 * @proxy: A #DBusDmovieProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_dmovie__call_play().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with dbus_dmovie__call_play().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_play_finish (
    DBusDmovie *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_play_sync:
 * @proxy: A #DBusDmovieProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.Play">Play()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See dbus_dmovie__call_play() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_play_sync (
    DBusDmovie *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Play",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_pause:
 * @proxy: A #DBusDmovieProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.Pause">Pause()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call dbus_dmovie__call_pause_finish() to get the result of the operation.
 *
 * See dbus_dmovie__call_pause_sync() for the synchronous, blocking version of this method.
 */
void
dbus_dmovie__call_pause (
    DBusDmovie *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Pause",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * dbus_dmovie__call_pause_finish:
 * @proxy: A #DBusDmovieProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_dmovie__call_pause().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with dbus_dmovie__call_pause().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_pause_finish (
    DBusDmovie *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_pause_sync:
 * @proxy: A #DBusDmovieProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.Pause">Pause()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See dbus_dmovie__call_pause() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_pause_sync (
    DBusDmovie *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Pause",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_stop:
 * @proxy: A #DBusDmovieProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.Stop">Stop()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call dbus_dmovie__call_stop_finish() to get the result of the operation.
 *
 * See dbus_dmovie__call_stop_sync() for the synchronous, blocking version of this method.
 */
void
dbus_dmovie__call_stop (
    DBusDmovie *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Stop",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * dbus_dmovie__call_stop_finish:
 * @proxy: A #DBusDmovieProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_dmovie__call_stop().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with dbus_dmovie__call_stop().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_stop_finish (
    DBusDmovie *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_stop_sync:
 * @proxy: A #DBusDmovieProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.Stop">Stop()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See dbus_dmovie__call_stop() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_stop_sync (
    DBusDmovie *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Stop",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_set_uri:
 * @proxy: A #DBusDmovieProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.SetUri">SetUri()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call dbus_dmovie__call_set_uri_finish() to get the result of the operation.
 *
 * See dbus_dmovie__call_set_uri_sync() for the synchronous, blocking version of this method.
 */
void
dbus_dmovie__call_set_uri (
    DBusDmovie *proxy,
    const gchar *arg_uri,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetUri",
    g_variant_new ("(s)",
                   arg_uri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * dbus_dmovie__call_set_uri_finish:
 * @proxy: A #DBusDmovieProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_dmovie__call_set_uri().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with dbus_dmovie__call_set_uri().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_set_uri_finish (
    DBusDmovie *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_set_uri_sync:
 * @proxy: A #DBusDmovieProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.SetUri">SetUri()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See dbus_dmovie__call_set_uri() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_set_uri_sync (
    DBusDmovie *proxy,
    const gchar *arg_uri,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetUri",
    g_variant_new ("(s)",
                   arg_uri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_seek:
 * @proxy: A #DBusDmovieProxy.
 * @arg_position: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.Seek">Seek()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call dbus_dmovie__call_seek_finish() to get the result of the operation.
 *
 * See dbus_dmovie__call_seek_sync() for the synchronous, blocking version of this method.
 */
void
dbus_dmovie__call_seek (
    DBusDmovie *proxy,
    gint64 arg_position,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Seek",
    g_variant_new ("(x)",
                   arg_position),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * dbus_dmovie__call_seek_finish:
 * @proxy: A #DBusDmovieProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_dmovie__call_seek().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with dbus_dmovie__call_seek().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_seek_finish (
    DBusDmovie *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__call_seek_sync:
 * @proxy: A #DBusDmovieProxy.
 * @arg_position: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-deepin-DeepinMovie.Seek">Seek()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See dbus_dmovie__call_seek() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
dbus_dmovie__call_seek_sync (
    DBusDmovie *proxy,
    gint64 arg_position,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Seek",
    g_variant_new ("(x)",
                   arg_position),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_dmovie__complete_play_paths:
 * @object: A #DBusDmovie.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-deepin-DeepinMovie.PlayPaths">PlayPaths()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
dbus_dmovie__complete_play_paths (
    DBusDmovie *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * dbus_dmovie__complete_play:
 * @object: A #DBusDmovie.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-deepin-DeepinMovie.Play">Play()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
dbus_dmovie__complete_play (
    DBusDmovie *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * dbus_dmovie__complete_pause:
 * @object: A #DBusDmovie.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-deepin-DeepinMovie.Pause">Pause()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
dbus_dmovie__complete_pause (
    DBusDmovie *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * dbus_dmovie__complete_stop:
 * @object: A #DBusDmovie.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-deepin-DeepinMovie.Stop">Stop()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
dbus_dmovie__complete_stop (
    DBusDmovie *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * dbus_dmovie__complete_set_uri:
 * @object: A #DBusDmovie.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-deepin-DeepinMovie.SetUri">SetUri()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
dbus_dmovie__complete_set_uri (
    DBusDmovie *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * dbus_dmovie__complete_seek:
 * @object: A #DBusDmovie.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-deepin-DeepinMovie.Seek">Seek()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
dbus_dmovie__complete_seek (
    DBusDmovie *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * DBusDmovieProxy:
 *
 * The #DBusDmovieProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * DBusDmovieProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #DBusDmovieProxy.
 */

struct _DBusDmovieProxyPrivate
{
  GData *qdata;
};

static void dbus_dmovie__proxy_iface_init (DBusDmovieIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (DBusDmovieProxy, dbus_dmovie__proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (DBusDmovieProxy)
                         G_IMPLEMENT_INTERFACE (DBUS_DMOVIE_TYPE_, dbus_dmovie__proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (DBusDmovieProxy, dbus_dmovie__proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (DBUS_DMOVIE_TYPE_, dbus_dmovie__proxy_iface_init));

#endif
static void
dbus_dmovie__proxy_finalize (GObject *object)
{
  DBusDmovieProxy *proxy = DBUS_DMOVIE__PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (dbus_dmovie__proxy_parent_class)->finalize (object);
}

static void
dbus_dmovie__proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  info = _dbus_dmovie__property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
dbus_dmovie__proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface com.deepin.DeepinMovie: %s (%s, %d)",
                 info->parent_struct.name,
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
dbus_dmovie__proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  info = _dbus_dmovie__property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "com.deepin.DeepinMovie", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) dbus_dmovie__proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
dbus_dmovie__proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_dbus_dmovie__interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], DBUS_DMOVIE_TYPE_);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, DBUS_DMOVIE_TYPE_);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
dbus_dmovie__proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  DBusDmovieProxy *proxy = DBUS_DMOVIE__PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dbus_dmovie__interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dbus_dmovie__interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static gdouble
dbus_dmovie__proxy_get_volume (DBusDmovie *object)
{
  DBusDmovieProxy *proxy = DBUS_DMOVIE__PROXY (object);
  GVariant *variant;
  gdouble value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Volume");
  if (variant != NULL)
    {
      value = g_variant_get_double (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean
dbus_dmovie__proxy_get_mute (DBusDmovie *object)
{
  DBusDmovieProxy *proxy = DBUS_DMOVIE__PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Mute");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gint64
dbus_dmovie__proxy_get_duration (DBusDmovie *object)
{
  DBusDmovieProxy *proxy = DBUS_DMOVIE__PROXY (object);
  GVariant *variant;
  gint64 value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Duration");
  if (variant != NULL)
    {
      value = g_variant_get_int64 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gint64
dbus_dmovie__proxy_get_position (DBusDmovie *object)
{
  DBusDmovieProxy *proxy = DBUS_DMOVIE__PROXY (object);
  GVariant *variant;
  gint64 value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Position");
  if (variant != NULL)
    {
      value = g_variant_get_int64 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
dbus_dmovie__proxy_init (DBusDmovieProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = dbus_dmovie__proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, DBUS_DMOVIE_TYPE__PROXY, DBusDmovieProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), dbus_dmovie__interface_info ());
}

static void
dbus_dmovie__proxy_class_init (DBusDmovieProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = dbus_dmovie__proxy_finalize;
  gobject_class->get_property = dbus_dmovie__proxy_get_property;
  gobject_class->set_property = dbus_dmovie__proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = dbus_dmovie__proxy_g_signal;
  proxy_class->g_properties_changed = dbus_dmovie__proxy_g_properties_changed;

  dbus_dmovie__override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (DBusDmovieProxyPrivate));
#endif
}

static void
dbus_dmovie__proxy_iface_init (DBusDmovieIface *iface)
{
  iface->get_volume = dbus_dmovie__proxy_get_volume;
  iface->get_mute = dbus_dmovie__proxy_get_mute;
  iface->get_duration = dbus_dmovie__proxy_get_duration;
  iface->get_position = dbus_dmovie__proxy_get_position;
}

/**
 * dbus_dmovie__proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-deepin-DeepinMovie.top_of_page">com.deepin.DeepinMovie</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call dbus_dmovie__proxy_new_finish() to get the result of the operation.
 *
 * See dbus_dmovie__proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
dbus_dmovie__proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (DBUS_DMOVIE_TYPE__PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.deepin.DeepinMovie", NULL);
}

/**
 * dbus_dmovie__proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_dmovie__proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with dbus_dmovie__proxy_new().
 *
 * Returns: (transfer full) (type DBusDmovieProxy): The constructed proxy object or %NULL if @error is set.
 */
DBusDmovie *
dbus_dmovie__proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return DBUS_DMOVIE_ (ret);
  else
    return NULL;
}

/**
 * dbus_dmovie__proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-deepin-DeepinMovie.top_of_page">com.deepin.DeepinMovie</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See dbus_dmovie__proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type DBusDmovieProxy): The constructed proxy object or %NULL if @error is set.
 */
DBusDmovie *
dbus_dmovie__proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (DBUS_DMOVIE_TYPE__PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.deepin.DeepinMovie", NULL);
  if (ret != NULL)
    return DBUS_DMOVIE_ (ret);
  else
    return NULL;
}


/**
 * dbus_dmovie__proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like dbus_dmovie__proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call dbus_dmovie__proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See dbus_dmovie__proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
dbus_dmovie__proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (DBUS_DMOVIE_TYPE__PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.deepin.DeepinMovie", NULL);
}

/**
 * dbus_dmovie__proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_dmovie__proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with dbus_dmovie__proxy_new_for_bus().
 *
 * Returns: (transfer full) (type DBusDmovieProxy): The constructed proxy object or %NULL if @error is set.
 */
DBusDmovie *
dbus_dmovie__proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return DBUS_DMOVIE_ (ret);
  else
    return NULL;
}

/**
 * dbus_dmovie__proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like dbus_dmovie__proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See dbus_dmovie__proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type DBusDmovieProxy): The constructed proxy object or %NULL if @error is set.
 */
DBusDmovie *
dbus_dmovie__proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (DBUS_DMOVIE_TYPE__PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.deepin.DeepinMovie", NULL);
  if (ret != NULL)
    return DBUS_DMOVIE_ (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * DBusDmovieSkeleton:
 *
 * The #DBusDmovieSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * DBusDmovieSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #DBusDmovieSkeleton.
 */

struct _DBusDmovieSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_dbus_dmovie__skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], DBUS_DMOVIE_TYPE_);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, DBUS_DMOVIE_TYPE_);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_dbus_dmovie__skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dbus_dmovie__interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_dbus_dmovie__skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dbus_dmovie__interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _dbus_dmovie__skeleton_vtable =
{
  _dbus_dmovie__skeleton_handle_method_call,
  _dbus_dmovie__skeleton_handle_get_property,
  _dbus_dmovie__skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
dbus_dmovie__skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return dbus_dmovie__interface_info ();
}

static GDBusInterfaceVTable *
dbus_dmovie__skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_dbus_dmovie__skeleton_vtable;
}

static GVariant *
dbus_dmovie__skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_dbus_dmovie__interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _dbus_dmovie__interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _dbus_dmovie__interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _dbus_dmovie__skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.deepin.DeepinMovie", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _dbus_dmovie__emit_changed (gpointer user_data);

static void
dbus_dmovie__skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _dbus_dmovie__emit_changed (skeleton);
}

static void dbus_dmovie__skeleton_iface_init (DBusDmovieIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (DBusDmovieSkeleton, dbus_dmovie__skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (DBusDmovieSkeleton)
                         G_IMPLEMENT_INTERFACE (DBUS_DMOVIE_TYPE_, dbus_dmovie__skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (DBusDmovieSkeleton, dbus_dmovie__skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (DBUS_DMOVIE_TYPE_, dbus_dmovie__skeleton_iface_init));

#endif
static void
dbus_dmovie__skeleton_finalize (GObject *object)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (object);
  guint n;
  for (n = 0; n < 4; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (dbus_dmovie__skeleton_parent_class)->finalize (object);
}

static void
dbus_dmovie__skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_dbus_dmovie__emit_changed (gpointer user_data)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "com.deepin.DeepinMovie",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_dbus_dmovie__schedule_emit_changed (DBusDmovieSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
dbus_dmovie__skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _dbus_dmovie__emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
dbus_dmovie__skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _dbus_dmovie__schedule_emit_changed (skeleton, _dbus_dmovie__property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
dbus_dmovie__skeleton_init (DBusDmovieSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = dbus_dmovie__skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, DBUS_DMOVIE_TYPE__SKELETON, DBusDmovieSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 4);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_DOUBLE);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_INT64);
  g_value_init (&skeleton->priv->properties[3], G_TYPE_INT64);
}

static gdouble
dbus_dmovie__skeleton_get_volume (DBusDmovie *object)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (object);
  gdouble value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_double (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean
dbus_dmovie__skeleton_get_mute (DBusDmovie *object)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gint64
dbus_dmovie__skeleton_get_duration (DBusDmovie *object)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (object);
  gint64 value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_int64 (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gint64
dbus_dmovie__skeleton_get_position (DBusDmovie *object)
{
  DBusDmovieSkeleton *skeleton = DBUS_DMOVIE__SKELETON (object);
  gint64 value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_int64 (&(skeleton->priv->properties[3]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
dbus_dmovie__skeleton_class_init (DBusDmovieSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = dbus_dmovie__skeleton_finalize;
  gobject_class->get_property = dbus_dmovie__skeleton_get_property;
  gobject_class->set_property = dbus_dmovie__skeleton_set_property;
  gobject_class->notify       = dbus_dmovie__skeleton_notify;


  dbus_dmovie__override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = dbus_dmovie__skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = dbus_dmovie__skeleton_dbus_interface_get_properties;
  skeleton_class->flush = dbus_dmovie__skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = dbus_dmovie__skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (DBusDmovieSkeletonPrivate));
#endif
}

static void
dbus_dmovie__skeleton_iface_init (DBusDmovieIface *iface)
{
  iface->get_volume = dbus_dmovie__skeleton_get_volume;
  iface->get_mute = dbus_dmovie__skeleton_get_mute;
  iface->get_duration = dbus_dmovie__skeleton_get_duration;
  iface->get_position = dbus_dmovie__skeleton_get_position;
}

/**
 * dbus_dmovie__skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-deepin-DeepinMovie.top_of_page">com.deepin.DeepinMovie</link>.
 *
 * Returns: (transfer full) (type DBusDmovieSkeleton): The skeleton object.
 */
DBusDmovie *
dbus_dmovie__skeleton_new (void)
{
  return DBUS_DMOVIE_ (g_object_new (DBUS_DMOVIE_TYPE__SKELETON, NULL));
}

